### ISSUE TITLE
workshop are not loading test cabinets automatically

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#115]

**Comment by WilsonBradley** [comment]
Worked as expected for me. Is it intermittent?
Also, regards to that, is it intentional to Voice test cabinet after exiting Joy? Ideally, it would stay, exiting / entering Joy would be frequent when testing. This becomes extra work if having to redrop a .zip cabinet in cabinets folder.

Also, this is mostly for testing Cabinet assets, correct? Meaning, not ideal for verifying which ROMs are compatible.

**Comment by curif** [comment]
Yes, it's only for testing. 
I tested it again, it's working ok. I uploaded a wrong zip file previously.
Closed.

**Comment by WilsonBradley** [comment]
?
Also, regards to that, is it intentional to remove test cabinet after exiting Joy? Ideally, it would stay, exiting / entering Joy would be frequent when testing. This becomes extra work if having to redrop a .zip cabinet in cabinets folder.

Also, this is mostly for testing Cabinet assets, correct? Meaning, not ideal for verifying which ROMs are compatible.
